### ISSUE TITLE
Colored point cloud offset / mismatch

### ISSUE THREAD

**Issue by cgsaxner** [microsoft/HoloLens2ForCV#43]
Hi!
I made some recordings of PV and DepthAHAT streams with the StreamRecorder and processed them with process_all.py to obtain colored point clouds.
In those point clouds, there is a quite large mismatch (I would guess around 2 cm) between depth and rgb information, as can be seen from this example:
![hl201](https://user-images.githubusercontent.com/29651139/96850276-ebc17800-1456-11eb-9c6a-b9e946463f82.png)

With the HoloLens1 using my own code, the matching is much better:
![hl103](https://user-images.githubusercontent.com/29651139/96850505-30e5aa00-1457-11eb-8890-96d51521dc9e.png)

Is this behavior expected, or is something wrong with my recordings? Is there anything I can do (except for adding a fixed offset) 
to obtain a better matching between DepthAHAT and PV?

Thanks!

**Comment by fbogo** [comment]
Currently, the matching between depth and PV frames based on timestamps is quite naive (given a depth frame, the closest PV frame in time is picked to get RGB values). So any motions could cause misalignments.
In order to try identify if this is strictly a problem with AHAT instead, could you please confirm if you observe the same behavior when obtaining point clouds from Long Throw Depth?

**Comment by cgsaxner** [comment]
I see, thanks for your reply. Here is a point cloud from Long Throw Depth:
![snapshot00](https://user-images.githubusercontent.com/29651139/97413968-b2c84e00-1903-11eb-9e3c-b29e9c2af503.png)

The problem looks quite the same, the RGB information seems to be shifted to the left wrt. the depth information.
After looking at some more frames and recordings, it looks to me like a systematic error, since the shift is always approximately the same, regardless of motion direction etc. So maybe some of the camera parameters are not quite right?

**Comment by kysucix** [comment]
Hi cgsaxner, 

I didn't experience such a systematic bias, I even tried with a fire extinguisher as well: 
![image](https://user-images.githubusercontent.com/1687493/97971713-bce6c280-1dc3-11eb-8548-e3fdd88b4fa8.png)

Which windows version are you using?

**Comment by cgsaxner** [comment]
Hi, this looks indeed much better than my results. 
I'm using Windows 10 Pro Version 10.0.19041 on my PC, the HoloLens 2 runs build 19041.1384.
Thanks!

**Comment by kysucix** [comment]
Could you try to make sure you're running the latest available build please?

**Comment by cgsaxner** [comment]
Sorry for the late reply, I did not have access to the device for the past days. After upgrading to the newest build on the dev channel and pulling the latest version from this repository, the problem still persists.
Long throw depth:
![snapshot01](https://user-images.githubusercontent.com/29651139/98789849-2e95c080-2403-11eb-9bd3-c0c15eb6e8e9.png)
AHAT depth:
![Inkedsnapshot00_LI](https://user-images.githubusercontent.com/29651139/98789997-5d139b80-2403-11eb-8d5f-6a7e1c0377be.jpg)
I also noticed that there seems to be a new problem with the AHAT reconstruction now, where some points seem to be wrongly reconstructed near the camera (red circle). These points are present in every AHAT point cloud I looked at, in some cases much more severe than in this example.

**Comment by wanglolly** [comment]
> Sorry for the late reply, I did not have access to the device for the past days. After upgrading to the newest build on the dev channel and pulling the latest version from this repository, the problem still persists.
> Long throw depth:
> ![snapshot01](https://user-images.githubusercontent.com/29651139/98789849-2e95c080-2403-11eb-9bd3-c0c15eb6e8e9.png)
> AHAT depth:
> ![Inkedsnapshot00_LI](https://user-images.githubusercontent.com/29651139/98789997-5d139b80-2403-11eb-8d5f-6a7e1c0377be.jpg)
> I also noticed that there seems to be a new problem with the AHAT reconstruction now, where some points seem to be wrongly reconstructed near the camera (red circle). These points are present in every AHAT point cloud I looked at, in some cases much more severe than in this example.

Hello!
I have exactly the same problem in the AHAT depth reconstruction currently. 
In each frame, there are some wrong reconstructed point near the camera itself, this is somehow weird and will be a seriously problem when preserving all the frames.
Does anyone have any idea how to solve it?
Thank you very much :)

**Comment by estherlxd** [comment]
Hi, 
I am also experiencing the same issue. I fixed my Hololens 2 on a tripod to avoid the camera motion, and used StreamRecorder App to capture PV and Long throw frames, so the RGB data should exactly match the 3D point clouds. But different from what I expected, after running process_all.py to obtain colored point clouds, I observed that the RGB information seems to be shifted to the left wrt. the depth information. And with depth distance between HL2 and objects increased, the size of the offset also becomes larger. 
With distance 40cm:
![image](https://user-images.githubusercontent.com/34557615/112396247-0a08f980-8cbd-11eb-969a-8696d93a82f6.png)
With distance 90cm:
![image](https://user-images.githubusercontent.com/34557615/112396517-83a0e780-8cbd-11eb-9666-7613c2974c08.png)

Does anyone have any idea how to solve it? Thanks!

**Comment by Fouksi** [comment]
Hi,

Did anybody managed to solve this issue?
I've experiencing the same thing.

 Thanks

**Comment by cgsaxner** [comment]
Hi, I eventually managed to kind of overcome this problem by calibrating the HoloLens cameras myself and by replacing the camera parameters loaded from files in the reconstruction code with my own. It seems like the on-board calibration of the HoloLens is just not very accurate. The calibration is quite challenging though, and it still does not look perfect. I used this toolbox:
https://github.com/RobVisLab/camera_calibration

**Comment by Fouksi** [comment]
I kind of fixed it manually by editing the rotation vector, adding a code line to the function 'project_on_pv' at the 'utils.py' script:
[...]
rvec = np.zeros(3)
**rvec[1] = 0.025**
tvec = np.zeros(3)
[...]

**Comment by kysucix** [comment]
It looks like this is fixed in #104 please try with latest master

**Comment by chenritiana** [comment]
hello,how did you get the points with color?I'm interested in this
